### ISSUE TITLE
python 2.7 support

### ISSUE THREAD

**Issue by tikismoke** [Julius2342/pyvlx#11]
As I understand asyncio is now need to use the new API.
Asyncio seems not compatible with Putin 2.7. So no way to have pylvx working on a 2.7 python instance?

**Comment by Julius2342** [comment]
im heavily depending on asyncio. You would need multithreadying with all its problems.

Where on earth are you still running python 2.7? Time for upgrade! :-)

**Comment by tikismoke** [comment]
Indeed but not possible in all case :)

**Comment by tikismoke** [comment]
To solve this problem i use https://github.com/3s1d/vlx2mqtt so my home automation get value of pyvlx through mqtt
