### ISSUE TITLE
Which IDE for debug

### ISSUE THREAD

**Issue by WoodsterDK** [Julius2342/pyvlx#12]
Hi,
Just a question regarding which IDE you use for development and debug?
I have used VS Code for various things, but can't seem to get the the paths set correctly for debugging from the sample into the module. Any experience/idea?

**Comment by Julius2342** [comment]
Well, my editor is `Vi` and my debugger `print()`  :)

[My colleges are pretty enthusiastic about PyCharm, but I never tried it.]

**Comment by WoodsterDK** [comment]
Nothing beats logging to console :)
Never tried PyCharm - VS Code supports breakpoints and lots of plugins, just can't get it to work to step into the module from the test application.
