### ISSUE TITLE
Garage Door not handled

### ISSUE THREAD

**Issue by werner-j** [Julius2342/pyvlx#28]
Hello @Julius2342,

I got the following message from PyVLX:

NodeTypeWithSubtype.GARAGE_DOOR_OPENER not implemented

Could you please add this to enable users to use PyVLX in conjunction with garage doors?

**Comment by Julius2342** [comment]
May you try a Pullrequest? the implementation should be trivial. (I guess it acts like any other opening device, but i dont have one so i cant try it out).

**Comment by tikismoke** [comment]
Look at hold/closed PR to implement roller shutter. It might be similar. And make test.

Le 30 juin 2019 12:54:05 GMT+02:00, Julius Mittenzwei <notifications@github.com> a écrit :
>May you try a Pullrequest? the implementation should be trivial. (I
>guess it acts like any other opening device, but i dont have one so i
>cant try it out).
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Julius2342/pyvlx/issues/28#issuecomment-507026661

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by werner-j** [comment]
https://github.com/Julius2342/pyvlx/pull/29

**Comment by werner-j** [comment]
I've added a test as well. Hope that's good for pull.
