### ISSUE TITLE
Tilt support for exterior blinds

### ISSUE THREAD

**Issue by pawlizio** [Julius2342/pyvlx#33]
I tried to understand what needs to be modified to support tilt functionality for exterior blinds. It seems KLF 200 provides this with Functional Parameter 3. But the API specification and your implementation are not so easy to understand.

I use home-assistant and moved from Somfy Tahoma to Velux KLF 200 in order to get rid of the somfy servers. However I recognized that my Raffstore don't support tilt functionality with the Velux integration.  

Would be great if someone can support.

**Comment by Julius2342** [comment]
*sigh*  i broke it again. This time i will fix it ...

**Comment by pawlizio** [comment]
@Julius2342 : Could you create a new release with #34 in order to adjust official HA velux component?

**Comment by Julius2342** [comment]
done
