### ISSUE TITLE
Enable velocity parameter

### ISSUE THREAD

**Issue by PhillyGilly** [Julius2342/pyvlx#342]
It isn't possible to control the speed of opening or closing devices even though this functionality exists in the KLF200 API.
The facility to control velocity is important where windows and blinds are fitted in bedrooms when fast operation may be too noisy.
The functions to get available velocities and set velocity are included in the Velux API v3.16 but not included in this interface.
Available settings for velocity are shown here:
![image](https://github.com/Julius2342/pyvlx/assets/56273663/e1e62ca6-61da-4cae-b842-5c594b3a9204)
In practical terms it would be desirable to be able to pass a desired velocity to the API, check that the node can accept the command and then execute it, incorporating these calls into the open/close commands.  

![image](https://github.com/Julius2342/pyvlx/assets/56273663/acfea655-9f1f-49ae-9ba2-b74e96ce8239)

**Comment by kenji21** [comment]
How does this is exposed / configured within Home Assistant ?

Edit: PR on HA hadn't did merged, another PR has been made : https://github.com/home-assistant/core/pull/163819

**Comment by wollew** [comment]
There is also the custom integration https://github.com/pawlizio/my_velux/ which has velocity integrated already, although I believe the velocity feature will probably not work right now, because it uses an older version of pyvlx which doesn't have [this fix](https://github.com/Julius2342/pyvlx/pull/576) yet.

**Comment by kenji21** [comment]
What I can confirm, it is that PyVLX at 0.2.33 runs finewith velocity with my KLF200 :

```
async def main():
    client = PyVLX(host=HOST, password=PASSWORD)

    await client.connect()
    await client.load_nodes()

    volets = [node for node in client.nodes if isinstance(node, RollerShutter)]

    await asyncio.gather(*[
        node.close(velocity=Velocity.SILENT) for node in volets
    ])
    print("Terminé.")

    await client.disconnect()

if __name__ == "__main__":
    asyncio.run(main())
```

As the manifest points to 0.2.26, you're right, it might not work : https://github.com/pawlizio/my_velux/blob/master/custom_components/velux/manifest.json#L17C1-L18C1
