### ISSUE TITLE
got timeout when addressing klf200

### ISSUE THREAD

**Issue by dirk777** [Julius2342/pyvlx#7]
**Issue:**
klf200 is responding after scene has completed, which means that the http request configured with 10s timeout will stop and raise an error, if scene takes more than 10s

**Solution:**
increase timeout or make it configurable
In my fork I already did this: https://github.com/dirk777/pyvlx/commit/6cdede0d913a81bd7a56c15b03de3ca17c6d7158
If you want, I can make another pull request out of it?

**Comment by Julius2342** [comment]
PR would be highly appreciated!

**Comment by Julius2342** [comment]
Hi @dirk777 : I will reject this issue. The new API/implementation does not have this problem, bc the communication works asynchronously.

**Comment by Julius2342** [comment]
btw, it would be great, if you could test the new API :-)
