### ISSUE TITLE
please push latest commit as new release 0.1.6 to pyPI

### ISSUE THREAD

**Issue by cellerich** [Julius2342/pyvlx#9]
Hi Julius

Thanks for your work, I was able to use it in my Home Automation project.
However I had to use the last commited version since I need a timeout of 60 seconds (thats how long it takes the shutters to open/close).
Could you please generate a new release and push it to PyPI so we get the extension with the Timeout parameter when pip installing.

Thanks

**Comment by Julius2342** [comment]
could you try?

**Comment by cellerich** [comment]
Works like a charm!
Thanks a lot
